name: Validate codecov.yaml

on:
  push:
    paths:
      - "codecov.yaml"
      - ".github/workflows/validate-codecov.yaml"
    branches: [ main ]
  pull_request:
    paths:
      - "codecov.yaml"
      - ".github/workflows/validate-codecov.yaml"
    branches: [ main ]

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Validate
        shell: bash
        run: |
          curl --fail --data-binary @codecov.yaml https://codecov.io/validate
